### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by axlroden** [pierre2jean/Zabbix-Templates#1]
I get the following error when importing:

Zabbix 2.4.7

Cannot find value map "RuckusAPStatus" used for item prototype "AP Status $1" of discovery rule "Ruckus APs" on "Template SNMP Ruckus Zonedirector".

**Comment by pierre2jean** [comment]
Hello

I forget to mention the Value maps i used.
Administration => General => Value Mapping => Create ValueMap 

RuckusAPStatus  
0 ⇒ Disconnected
1 ⇒ Connected
2 ⇒ ApprovalPending
3 ⇒ UpgradingFirmware
4 ⇒ Provisioning
ruckusZDEthStatus  
1 ⇒ Up
2 ⇒ Down

**Comment by axlroden** [comment]
perfect import works now.

**Comment by axlroden** [comment]
Everything but the Ruckus AP discovery works now. I'm getting alot of these errors:

Cannot create item: item with the same key "ruckusZDWLANAPNumSta[]" already exists

**Comment by axlroden** [comment]
what firmware version are you basing your SNMP on ?

**Comment by pierre2jean** [comment]
Hi Alex

We use version 9.10.0.0 build 218 . 
Which version are you running and what type of ZoneDirector do you use?
Are there AP's that use the same name?

**Comment by axlroden** [comment]
this is a ZD3000 on 9.8.2, no AP's with same name though.
I'll try a few others as well before I start digging into the MIB :)

**Comment by pierre2jean** [comment]
It seems that there is no ruckusZDWLANAPNumSta key found in the SNMP Reference guide from Ruckus in version 9.8 (https://support.ruckuswireless.com/documents/456-zonedirector-9-8-snmp-reference-guide). 
You can delete this item from the discovery or upgrade to 9.10 or higher

**Comment by axlroden** [comment]
Works on 9.10, just tested it. Are you able to see the discovered AP's somewhere ? Or only get warnings with AP Down ?
